apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: train-schedule
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31110
